//
//  EmojiDataHelper.m
//  MTMessageKeyBoardDemo
//
//  Created by 董徐维 on 2016/12/21.
//  Copyright © 2016年 Mr.Tung. All rights reserved.
//

#import "EmojiDataHelper.h"

@implementation EmojiDataHelper
+ (EmojiDataHelper *)shareEmojiData
{
    static EmojiDataHelper *emojiDataHelper = nil;
    static dispatch_once_t predicate;
    dispatch_once(&predicate, ^{
        emojiDataHelper = [[self alloc] init];
    });
    return emojiDataHelper;
}

- (void)initEmojiData
{
    _emotions = @[@"[微笑]",
                  @"[大笑]",
                  @"[憨笑]",
                  @"[傻笑]",
                  @"[坏笑]",
                  @"[冷笑]",
                  @"[狞笑]",
                  @"[苦笑]",
                  @"[强笑]",
                  @"[嘲笑]",
                  @"[挤眼]",
                  @"[得意]",
                  @"[美了]",
                  @"[抱抱]",
                  @"[讨好]",
                  @"[调皮]",
                  @"[可爱]",
                  @"[耀眼]",
                  @"[兴奋]",
                  @"[鬼脸]",
                  @"[咧嘴]",
                  @"[无奈]",
                  @"[好奇]",
                  @"[怀疑]",
                  @"[呆呆]",
                  @"[哼~]",
                  @"[不开心]",
                  @"[可怜]",
                  @"[痛苦]",
                  @"[想哭]",
                  @"[委屈]",
                  @"[憋屈]",
                  @"[流泪]",
                  @"[大哭]",
                  @"[生气]",
                  @"[咒骂]",
                  @"[不满]",
                  @"[发火]",
                  @"[暴躁]",
                  @"[狂暴]",
                  @"[吃惊]",
                  @"[惊讶]",
                  @"[惊喜]",
                  @"[惊奇]",
                  @"[惊呆]",
                  @"[惊恐]",
                  @"[震惊]",
                  @"[不服]",
                  @"[不忿]",
                  @"[挑衅]",
                  @"[呸呸]",
                  @"[藐视]",
                  @"[作呕]",
                  @"[呕吐]",
                  @"[嫌弃]",
                  @"[吓人]",
                  @"[害怕]",
                  @"[崩溃]",
                  @"[OMG]",
                  @"[捂脸]",
                  @"[色色]",
                  @"[花痴]",
                  @"[飞吻]",
                  @"[亲亲]",
                  @"[献爱心]",
                  @"[送玫瑰]",
                  @"[美丽]",
                  @"[嘘~]",
                  @"[晕了]",
                  @"[困了]",
                  @"[闭嘴]",
                  @"[害羞]",
                  @"[祈祷]",
                  @"[再见]",
                  @"[无辜]",
                  @"[吃东西]",
                  @"[打哈气]",
                  @"[乌眼青]",
                  @"[累成狗]",
                  @"[大咖]",
                  @"[偷笑]",
                  @"[鄙视]",
                  @"[痛苦]",
                  @"[尴尬]",
                  @"[傲慢]",
                  @"[擦汗]",
                  @"[讥讽]",
                  @"[疑惑]",
                  @"[白眼]",
                  @"[胜利]"];
    
    _images = @[[UIImage imageNamed:@"emotion0001"],
                [UIImage imageNamed:@"emotion0002"],
                [UIImage imageNamed:@"emotion0003"],
                [UIImage imageNamed:@"emotion0004"],
                [UIImage imageNamed:@"emotion0005"],
                [UIImage imageNamed:@"emotion0006"],
                [UIImage imageNamed:@"emotion0007"],
                [UIImage imageNamed:@"emotion0008"],
                [UIImage imageNamed:@"emotion0009"],
                [UIImage imageNamed:@"emotion0010"],
                [UIImage imageNamed:@"emotion0011"],
                [UIImage imageNamed:@"emotion0012"],
                [UIImage imageNamed:@"emotion0013"],
                [UIImage imageNamed:@"emotion0014"],
                [UIImage imageNamed:@"emotion0015"],
                [UIImage imageNamed:@"emotion0016"],
                [UIImage imageNamed:@"emotion0017"],
                [UIImage imageNamed:@"emotion0018"],
                [UIImage imageNamed:@"emotion0019"],
                [UIImage imageNamed:@"emotion0020"],
                [UIImage imageNamed:@"emotion0021"],
                [UIImage imageNamed:@"emotion0022"],
                [UIImage imageNamed:@"emotion0023"],
                [UIImage imageNamed:@"emotion0024"],
                [UIImage imageNamed:@"emotion0025"],
                [UIImage imageNamed:@"emotion0026"],
                [UIImage imageNamed:@"emotion0027"],
                [UIImage imageNamed:@"emotion0028"],
                [UIImage imageNamed:@"emotion0029"],
                [UIImage imageNamed:@"emotion0030"],
                [UIImage imageNamed:@"emotion0031"],
                [UIImage imageNamed:@"emotion0032"],
                [UIImage imageNamed:@"emotion0033"],
                [UIImage imageNamed:@"emotion0034"],
                [UIImage imageNamed:@"emotion0035"],
                [UIImage imageNamed:@"emotion0036"],
                [UIImage imageNamed:@"emotion0037"],
                [UIImage imageNamed:@"emotion0038"],
                [UIImage imageNamed:@"emotion0039"],
                [UIImage imageNamed:@"emotion0040"],
                [UIImage imageNamed:@"emotion0041"],
                [UIImage imageNamed:@"emotion0042"],
                [UIImage imageNamed:@"emotion0043"],
                [UIImage imageNamed:@"emotion0044"],
                [UIImage imageNamed:@"emotion0045"],
                [UIImage imageNamed:@"emotion0046"],
                [UIImage imageNamed:@"emotion0047"],
                [UIImage imageNamed:@"emotion0048"],
                [UIImage imageNamed:@"emotion0049"],
                [UIImage imageNamed:@"emotion0050"],
                [UIImage imageNamed:@"emotion0051"],
                [UIImage imageNamed:@"emotion0052"],
                [UIImage imageNamed:@"emotion0053"],
                [UIImage imageNamed:@"emotion0054"],
                [UIImage imageNamed:@"emotion0055"],
                [UIImage imageNamed:@"emotion0056"],
                [UIImage imageNamed:@"emotion0057"],
                [UIImage imageNamed:@"emotion0058"],
                [UIImage imageNamed:@"emotion0059"],
                [UIImage imageNamed:@"emotion0060"],
                [UIImage imageNamed:@"emotion0061"],
                [UIImage imageNamed:@"emotion0062"],
                [UIImage imageNamed:@"emotion0063"],
                [UIImage imageNamed:@"emotion0064"],
                [UIImage imageNamed:@"emotion0065"],
                [UIImage imageNamed:@"emotion0066"],
                [UIImage imageNamed:@"emotion0067"],
                [UIImage imageNamed:@"emotion0068"],
                [UIImage imageNamed:@"emotion0069"],
                [UIImage imageNamed:@"emotion0070"],
                [UIImage imageNamed:@"emotion0071"],
                [UIImage imageNamed:@"emotion0072"],
                [UIImage imageNamed:@"emotion0073"],
                [UIImage imageNamed:@"emotion0074"],
                [UIImage imageNamed:@"emotion0075"],
                [UIImage imageNamed:@"emotion0076"],
                [UIImage imageNamed:@"emotion0077"],
                [UIImage imageNamed:@"emotion0078"],
                [UIImage imageNamed:@"emotion0079"],
                [UIImage imageNamed:@"emotion0080"],
                [UIImage imageNamed:@"emotion0081"],
                [UIImage imageNamed:@"emotion0082"],
                [UIImage imageNamed:@"emotion0083"],
                [UIImage imageNamed:@"emotion0084"],
                [UIImage imageNamed:@"emotion0085"],
                [UIImage imageNamed:@"emotion0086"],
                [UIImage imageNamed:@"emotion0087"],
                [UIImage imageNamed:@"emotion0088"]];
    
}
@end
